server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: library_user
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
